### ISSUE TITLE
(UndefinedFunctionError) function :cbor.app/1 is undefined (module :cbor is not available)

### ISSUE THREAD

**Issue by ritou** [ritou/elixir-web_authn_lite#4]
```
$ mix deps.clean --all
$ mix deps.get
* Getting cbor (https://github.com/yjh0502/cbor-erlang.git)
remote: Enumerating objects: 42, done.        
remote: Total 42 (delta 0), reused 0 (delta 0), pack-reused 42        
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  base64url 0.0.1
  jason 1.1.2
  jose 1.8.4
* Getting jose (Hex package)
* Getting jason (Hex package)
* Getting base64url (Hex package)
$ mix test
==> base64url (compile)
Compiled src/base64url.erl
==> jose
Compiling 89 files (.erl)
Compiling 8 files (.ex)
Generated jose app
==> jason
Compiling 8 files (.ex)
Generated jason app
===> Compiling cbor
==> web_authn_lite
Compiling 14 files (.ex)
Generated web_authn_lite app
..................

Finished in 0.2 seconds
3 doctests, 15 tests, 0 failures

Randomized with seed 619071
$ mix hex.build
** (UndefinedFunctionError) function :cbor.app/1 is undefined (module :cbor is not available)
    :cbor.app({:cbor, nil, [github: "yjh0502/cbor-erlang"]})
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (hex) lib/mix/tasks/hex.build.ex:251: Mix.Tasks.Hex.Build.dependencies/0
    (hex) lib/mix/tasks/hex.build.ex:130: Mix.Tasks.Hex.Build.prepare_package/0
    (hex) lib/mix/tasks/hex.build.ex:91: Mix.Tasks.Hex.Build.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
```

**Comment by ritou** [comment]
This seems to be caused by fetching the Erlang library from github.
I plan to use `elixir-cbor` instead of Erlang library.
However, the processing result of the `elixir-cbor` library is incorrect, sending a pull request.
https://github.com/masonforest/elixir-cbor/pull/2
