### ISSUE TITLE
Does not work when using jose greater than version 1.10.0.

### ISSUE THREAD

**Issue by tashirosota** [ritou/elixir-web_authn_lite#9]
HI ritou.

When updating OTP to 24 series, it is necessary to update jose due to the influence of changes around crypto.
But web_authn_lite does not work when jose v1.10.0.

```elixir
defp deps do
  [
    {:jose, "1.10.0"}, # Successes when 1.9
    ...
  ]
end
```

stacktrace example.

```
** (CaseClauseError) no case clause matching: 43
stacktrace:
  (jose 1.10.0) src/base/jose_base64url.erl:205: :jose_base64url."-decode!/2-lbc$^0/2-0-"/2
  (jose 1.10.0) src/base/jose_base64url.erl:205: :jose_base64url.decode!/2
  (jose 1.10.0) src/jwk/jose_jwk_kty_rsa.erl:462: :jose_jwk_kty_rsa.from_map_rsa_public_key/2
  (jose 1.10.0) src/jwk/jose_jwk.erl:300: :jose_jwk.from_map/1
  (jose 1.10.0) lib/jose/jwk.ex:135: JOSE.JWK.from_map/1
  (web_authn_lite 0.1.4) lib/web_authn_lite/credential_public_key/rs256.ex:20: WebAuthnLite.CredentialPublicKey.RS256.from_cbor_map/1
  test/lib/web_authn_lite/credential_public_key_test.exs:52: (test)
```

**Comment by tashirosota** [comment]
Probably due to the base64url being out of dependency.

jose 1.9.0
```erlang
# src/jwk/jose_jwk_kty_rsa.erl:462
%% @private
from_map_rsa_public_key(F = #{ <<"e">> := E }, Key) ->
	from_map_rsa_public_key(maps:remove(<<"e">>, F), Key#'RSAPublicKey'{ publicExponent = crypto:bytes_to_integer(base64url:decode(E)) });
from_map_rsa_public_key(F = #{ <<"n">> := N }, Key) ->
	from_map_rsa_public_key(maps:remove(<<"n">>, F), Key#'RSAPublicKey'{ modulus = crypto:bytes_to_integer(base64url:decode(N)) });
from_map_rsa_public_key(F, Key) ->
	{Key, F}.
```

jose 1.10.0
```erlang
%% @private
from_map_rsa_public_key(F = #{ <<"e">> := E }, Key) ->
	from_map_rsa_public_key(maps:remove(<<"e">>, F), Key#'RSAPublicKey'{ publicExponent = crypto:bytes_to_integer(jose_jwa_base64url:decode(E)) });
from_map_rsa_public_key(F = #{ <<"n">> := N }, Key) ->
	from_map_rsa_public_key(maps:remove(<<"n">>, F), Key#'RSAPublicKey'{ modulus = crypto:bytes_to_integer(jose_jwa_base64url:decode(N)) });
from_map_rsa_public_key(F, Key) ->
	{Key, F}.
```

**Comment by tashirosota** [comment]
Arg N is the same value.

**Comment by tashirosota** [comment]
```erlang
% v1.10.0 jose_jwa_base64url:decode
-module(jose_base64url).
'decode!'(Input, Opts) when ?is_iodata(Input) andalso is_map(Opts) ->
  Padding = maps:get('padding', Opts, nil),
  Size = erlang:iolist_size(Input),
  Offset =
    case Padding of
      _ when (Padding == false orelse Padding == nil) andalso Size =< 4 ->
        0;
      _ when (Padding == false orelse Padding == nil) andalso (Size rem 4) =/= 0 ->
        Size - (Size rem 4);
      _ when (Padding == false orelse Padding == nil) ->
        Size - 4;
      _ when (Padding == true orelse Padding == nil) andalso Size >= 4 ->
        Size - 4;
      _ ->
        erlang:error({badarg, [Input, Opts]})
    end,
  << Head0:Offset/binary, Tail0/binary >> = ?to_binary(Input),
  Head = << << (?B64URL_TO_INT(V)):6 >> || << V >> <= Head0 >>,
  Tail =
    case Padding of
      false ->
        case Tail0 of
          << T0:8, T1:8 >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1) bsr 4):2 >>;
          << T0:8, T1:8, T2:8 >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1)):6, (?B64URL_TO_INT(T2) bsr 2):4 >>;
          << T:4/binary >> ->
            << << (?B64URL_TO_INT(V)):6 >> || << V >> <= T >>;
          <<>> ->
            <<>>;
          _ ->
            erlang:error({badarg, [Input, Opts]})
        end;
      nil ->
        case Tail0 of
          << T0:8, T1:8, $=, $= >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1) bsr 4):2 >>;
          << T0:8, T1:8, T2:8, $= >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1)):6, (?B64URL_TO_INT(T2) bsr 2):4 >>;
          << T0:8, T1:8 >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1) bsr 4):2 >>;
          << T0:8, T1:8, T2:8 >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1)):6, (?B64URL_TO_INT(T2) bsr 2):4 >>;
          << T:4/binary >> ->
            << << (?B64URL_TO_INT(V)):6 >> || << V >> <= T >>;
          <<>> ->
            <<>>
        end;
      true ->
        case Tail0 of
          << T0:8, T1:8, $=, $= >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1) bsr 4):2 >>;
          << T0:8, T1:8, T2:8, $= >> ->
            << (?B64URL_TO_INT(T0)):6, (?B64URL_TO_INT(T1)):6, (?B64URL_TO_INT(T2) bsr 2):4 >>;
          << T:4/binary >> ->
            << << (?B64URL_TO_INT(V)):6 >> || << V >> <= T >>;
          <<>> ->
            <<>>;
          _ ->
            erlang:error({badarg, [Input, Opts]})
        end
    end,
  << Head/binary, Tail/binary >>;

% v1.9.0 base64url:decode(N)
-module(base64url).
decode(Bin) when is_binary(Bin) ->
  Bin2 = case byte_size(Bin) rem 4 of
    % 1 -> << Bin/binary, "===" >>;
    2 -> << Bin/binary, "==" >>;
    3 -> << Bin/binary, "=" >>;
    _ -> Bin
  end,
  base64:decode(<< << (urldecode_digit(D)) >> || <<D>> <= Bin2 >>);
```

**Comment by tashirosota** [comment]
https://github.com/tashirosota/elixir-web_authn_lite/pull/3

**Comment by ritou** [comment]
I am using JOSE in a module called CredentialPublicKey for key management.

When calling "JOSE.JWK.from_map", it seems that I have been mistakenly putting Base64 encoded values where Base64 URL encoded values are expected.

Fixing this will eliminate the error, but may render existing keys unusable.
I will check on this.
